quiz/polls/urls.py
from django.urls import path
from polls.forms import NameForm

from . import views

app_name= 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/<int:question_id>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('/about', views.about, name='about'),
    #path('save_results/', views.SaveResultsView.as_view, name='save_results'),
    #path('<int:question_id>/answers/', views.answers, name='answers'),
    #path('answers/', views.seeAllAnswers.as_view(), name='allAnswers'),
    
]

quiz/quiz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('users/', include('users.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

quiz/polls/models.py
from django.db import models
from django_random_queryset import RandomManager
#import reverse
from django.urls import reverse


# Answers must be written out within 200 characters of text.
# An answer may be pulled randomly for any question as a false answer.
class Subject(models.Model):
    objects = RandomManager()
    subject_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.subject_text


class Question(models.Model):
    objects = RandomManager()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    answers = models.CharField(max_length=200)
    
    def __str__(self):
        return self.question_text + self.answers
    
    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.pk})

class Answer(models.Model):
    objects = RandomManager()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)

    def __str__(self):
        return self.answer_text

    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.question.id, 'pk2': self.pk})

class Choice(models.Model):
    question = models.ForeignKey(Answer, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text 

class Counter(models.Model):
    counter = models.IntegerField(default=0, null=True)

    def __str__(self):
        return str(self.counter)

quiz/polls/forms.py
from django import forms
from .models import Subject, Question, Answer




class NameForm(forms.Form):
    
    model = Question, Subject
    def get_question(self):
        question = Subject.objects.filter(id=3)
        return question
    #submit= forms.CharField(widget=forms.TextInput(attrs={'type': 'submit', 'value': 'Submit', 'name': 'submit'}))
    #next = forms.CharField(widget=forms.TextInput(attrs={'type': 'submit', 'value': 'Next', 'name': 'next'}))
        
    

quiz/polls/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from .models import Subject, Question, Answer, Choice, Counter
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import NameForm
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Subject.objects.order_by('-pub_date')[:5]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        print(Question.objects.filter(subject=1).random(1).get(subject_id=1))
        context['question'] = Question.objects.filter(subject=1).random(1).get(subject_id=1)
        return context


class DetailView(generic.ListView, FormView):
    model = Question, Subject, Answer, Choice
    template_name = 'polls/detail.html'
    context_object_name = 'question_list'
    success_url = 'answers'
    form_class = NameForm
    #test_array = []
    object_list = {}
    object = Question.objects.all()
    context={}
    
    def get_queryset(self):
        data = Question.objects.filter(subject=self.kwargs['pk'])

        #return a random question from the queryset
        return data.random(1)

    def get_context_data(self, **kwargs):
        # get context data that can be used in the template
        context = super().get_context_data(**kwargs)
       
        context['counter'] = Counter.objects.get(pk=1)
        context['choices'] = Choice.objects.all()
        context['questions'] = Question.objects.filter(subject=self.kwargs['pk']).random(10)
        return context

    def form_valid(self, form, *args, **kwargs):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
       
        form = NameForm(self.request.POST)
        
        if 'next' in self.request.POST:
            
            question = get_object_or_404(Question, pk=self.request.POST.get('question'))
            #question = self.test_array[0][0]
            #print(self.test_array)
            #if self.test_array[0]:
                #self.test_array.pop()
            print(question.id)
            print(self.request.POST.get('question'))
            
            if str(question.id) in self.request.POST.get('question'):
                question = get_object_or_404(Question, pk=self.request.POST.get('question'))

            #if question.id == Choice.objects.get(fk=self.request.POST.get('question')).id:
            #print(self.request.POST)
            try:
                
                selected_choice = question.answer_set.get(pk=self.request.POST.get('choice'))
                #print(selected_choice)
            except (KeyError, Answer.DoesNotExist):
                # Redisplay the question voting form.
                return render(self.request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "You didn't select a choice.",
                })
            else:
                
                if Choice.objects.all().count() >= 10:
                    Choice.objects.all().delete()
                    Counter.objects.filter(pk=1).update(counter=0)
                answer = Answer.objects.get(pk=selected_choice.id)
                
                q = Choice.objects.create(choice_text=selected_choice.answer_text, question=answer)
                q.save()
                
                if selected_choice.answer_text == question.answers:
                    c = Counter.objects.get(pk=1)
                    c.counter += 1
                    c.save()
            
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.

                if Choice.objects.all().count() >= 10:
                    
                
                    return HttpResponseRedirect(reverse('polls:results', args=(self.kwargs['pk'], )))

            return HttpResponseRedirect(reverse('polls:detail', args=(self.kwargs['pk'], self.request.POST.get('question'))))
        
        elif 'submit' in self.request.POST:

            question = get_object_or_404(Question, pk=self.request.POST['question'])

            try:
                
                selected_choice = question.answer_set.get(pk=self.request.POST['choice'])
                print(selected_choice)

            except (KeyError, Answer.DoesNotExist):
                # Redisplay the question voting form.
                return render(self.request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "You didn't select a choice.",
                })
            else:
                
                if Choice.objects.all().count() >= 10:
                    Choice.objects.all().delete()
                    Counter.objects.filter(pk=1).update(counter=0)

                answer = Answer.objects.get(pk=selected_choice.id)
                q = Choice.objects.create(choice_text=selected_choice.answer_text, question=answer)
                q.save()

                if selected_choice.answer_text == question.answers:
                    c = Counter.objects.get(pk=1)
                    c.counter += 1
                    c.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse('polls:results', args=(self.kwargs['pk'],) ))

            
        return super().form_valid(form)

    
    
class ResultsView(generic.DetailView):
    model = Subject
    template_name = 'polls/results.html'
   

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['counter'] = Counter.objects.get(pk=1)
        context['choice'] = Choice.objects.all()
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])


        return context

    '''def form_valid(self, form, *args, **kwargs):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form=NameForm(self.request.GET)
        print(self.request.GET)
        
        if 'retry' in self.request.GET:
            return HttpResponseRedirect(reverse('polls:detail', args=(self.kwargs['pk'],)))
        
        return super().form_valid(form)'''

'''class SaveResultsView(LoginRequiredMixin, generic.ListView):
    model = Counter
    template_name = 'polls/save.html'
    success_url = reverse_lazy('polls:save_results')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form) 

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['counter'] = Counter.objects.get(pk=1)
        context['choice'] = Choice.objects.all()
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        
        return context

    def get_queryset(self):
        return Counter.objects.get(pk=1)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)''' 


def about(request):

    return render(request, 'polls/about.html', {'title': 'About'})
    


    

quiz/polls/templates/polls/about.html
{% extends "polls/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <p>This is a website that allows you to practice questions for middle schoolers.</p>
    <div>
    <p>Created by: <a href="https://github.com/electricman991" target="_blank">Braiden Sommer</a></p>
    <p><a href="https://github.com/jonecars" target="_blank"> Carson Jones</a></p>
    <p><a href="https://github.com/GetHelpPlz" target="_blank"> Noah Li</a></p>
    <p><a href="https://github.com/W33bWhacker" target="_blank"> Josey Harger</a></p>
    <p><a href="https://github.com/j-dabling" target="_blank"> Jacob Dabling</a></p>
    
    
    </div>
    
</body>
</html>
{% endblock content %}

quiz/polls/templates/polls/answers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{$ url 'polls:answers' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ subject.subject_text }}</h1></legend>
            {% if error_message %}<p>Consider this marker 4.5, also error: <strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in subject.question_set.all %}
                <!--<input type="radio" name="answer_choice" id="answer_choice{{ forloop.counter }}" value="{{ answer.id }}">-->
                <h4>{{ choice.question_text }}</h4>
                <p>The correct answer is: {{ choice.answers }}</p><br>
               
                
                
            {% endfor %}
        </fieldset>
        <input type="submit" value="See Answers">
    
    </form>
</body>
</html>

quiz/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <title>inQUIZitor</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'polls:index' %}">inQUIZitor</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'polls:index' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'polls:about' %}">About</a>
            </div>

            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      {% block content %} {% endblock %}
    </main>
</body>
</html>

quiz/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'detail.css'%}" />
    <title>Questions</title>
</head>
<body>
   
    <form  method="post" enctype="multipart/form-data">
    
        {% csrf_token %}
        
        <fieldset >
            <legend id="topic"><h1 id="topic">{{ subject.subject_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            
            
            {% for choice in question_list %} 

                <p class="question-instructions">Select the answer that you belive to be correct and click the next button to go to the next question. If you want to check your progress
                    you can click the submit button which will show you which ones you got correct.
                </p>
                
                <p class="counter">Question {{ choices.count }}/10</p> 
                <p id="questions">{{ choice.question_text }}</p><br>
                

                {% if choice.question_text == "What must a rectangle have to make it a rectangle?"%}
                    <p>A: Four sides</p>
                    <p>B: Four right angles</p>
                    <p>C: Three equal sides</p>
                    <p>D: Four equal angles</p>
                {% elif choice.question_text == "Josh claims that these triangles are similar by SSS. Do you agree or disagree with Josh?"%}
                    <img src="/static/Triangles.png" alt="Triangles"> <br>

                {% elif choice.question_text == "Use f(x) and g(x) to find g(x) - f(x)."%} 
                    <p>Here, f(x) = -x + 5 and g(x) = 3x + 2.</p>
                
                {% elif choice.question_text == "Rewrite the equation below using only the Symmetric Property of Equality" %}
                    <p>3x + 2x + 1 = 4x + 8</p>
                {% endif %}
                
                {% for answer in choice.answer_set.all %}
                    <!-- create input button that returns post data -->
                    
                    <input type="radio" name="choice" id="choice{{forlopp.counter}}" value="{{ answer.id}}" >
                    <label for="choice{{forlopp.counter}}" id="choice">{{ answer.answer_text }}</label><br>
                {% endfor %}
                
            {% endfor %} 
        </fieldset>
       
        
        <input id="submit" type="submit" value="Submit" name="submit">
        {% for question in question_list %}
        <input type="hidden" name="question" value="{{ question.id }}">
            {% for answer in question.answer_set.all %}
                {% for choice in answer.choice_set.all %}
                    <input type="hidden" name="answer" value="{{ choice.id }}">
                {% endfor %}
            {% endfor %}
        {% endfor %}
        <input id="next" type="submit" value="Next" name="next"> 
        
    </form>
    
</body>
</html>
{% endblock content %}

quiz/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" type='text/css' href="{% static 'index.css'%}" />

    <title>Subjects</title>
</head>
<body>
    <h1 id="title">
        inQUIZitor
    </h1>
    <h2 id="subheading">
        Practice Questions<br>for<br>Middle Schoolers
    </h2>
    <p id="instruction">Select a subject you'd like to practice:</p>
    
    {% if latest_question_list %}
    <ul>
    {% for subject in latest_question_list %}
   
    <li><a href="{% url 'polls:detail' subject.id question.id %}"><button id="subject{{forloop.counter}}" class="subject">{{ subject.subject_text }}</button></a></li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>
{% endblock content %}

quiz/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'results.css'%}" />
</head>
<body>
    <h1>{{ subject.subject_text }}</h1>
    <br>

    <p class="result-instructions">Here is a list of the questions that you answered with the correct answer shown in green and your answer in red. If you only see 
    the correct answer, then you got the question correct. If you see both your answer and the correct answer, then you got the question
    wrong. Your score is shown at the bottom of the page.
    </p>
    <br>

<ul>

    {% for question in subject.question_set.all %}
        
        {% for answer in question.answer_set.all %}
            {% for choice in answer.choice_set.all %}
            {% if choice.choice_text == question.answers %}

            <div>
                <div> <p id="question"><b> Question: </b>{{ question.question_text }} </p> </div>
                <div id="answers">
                <div id ="correct"><p>Correct Answer:</p> {{ question.answers }}</div></div>
                <br><br></div>

            {% else %} 
            <div>
                <div> <p id="question"><b> Question: </b>{{ question.question_text }} </p> </div>
                <div id="answers"> <div id="youranswer"><p>Your Answer:</p> {{ choice.choice_text }} </div>
                <div id="correct"><p>Correct Answer:</p> {{ question.answers }}</div></div>
                <br><br></div>

            {% endif %}
            
            {% endfor %}
        {% endfor %}

    {% endfor %}
    <p class="points"> Points: {{ counter }}/{{ choice.count }} </p>
</ul>

<form method="GET" action="{% url 'polls:detail' subject.id question.id %}">
    <input type="submit" name="retry" value="Retry">
    <!--<input type="submit" name="save" value="Save Results" > -->
</form>

    
</body>
</html>

{% endblock %}